spring.application.name=SkillStorm

spring.datasource.url=JDBC_URL
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always
spring.sql.init.platform=mysql
spring.jpa.defer-datasource-initialization=true
